version: 2.1
jobs:
  build_check_install:
    docker:
      - image: rocker/tidyverse:3.6.3
    steps:
      - checkout:
          path: rtables
      - run:
          name: "Build R package"
          command: |
            R CMD build rtables
            echo "export PKG=$(echo *.tar.gz)" >> $BASH_ENV
      - run:
          name: "Check R package"
          command: |
            R CMD check --no-manual ${PKG}
            result=$(tail -1 rtables.Rcheck/00check.log)
            [[ $result = Status:* ]] || echo "could not get Status line"; set -o errexit
            [[ $result = *"Error"* ]] && echo "checks result in errors"; set -o errexit
      - run:
          name: "Install R package"
          command: R CMD INSTALL ${PKG}
      - store_artifacts:
          path: rtables.Rcheck/00check.log
          destination: 00check.log
      - store_test_results:
          path: rtables.Rcheck/tests
      - persist_to_workspace:
          root: ./
          paths:
            - "*.tar.gz"

  roxygen:
    docker:
      - image: rocker/tidyverse:3.6.3
    steps:
      - checkout
      - run:
          name: "check if manuals are upto date with roxygen comments"
          command: |
            R -e "roxygen2::roxygenize('.', roclets = c('rd', 'collate', 'namespace'))"
            if [[ -z $(git status -s) ]]
            then
              echo "manuals are not upto date with roxygen comments"
              echo "please rerun roxygen2::roxygenize('.', roclets = c('rd', 'collate', 'namespace'))"
              set -o errexit
            else
              echo "manuals are upto date with roxygen comments"
            fi

  pkgdown:
    docker:
      - image: rocker/tidyverse:3.6.3
    steps:
      - checkout:
          path: rtables
      - run:
          name: "create pkgdown website"
          command: R -e 'pkgdown::build_site("rtables", devel = FALSE)'
      - store_artifacts:
          path: rtables/docs
          destination: pkgdown

  # TODOs:
  #   docker:
  #     - image: cimg/base:2020.01
  #   steps:
  #     - checkout:
  #         path: rtables
  #     - run:
  #         command: grep -R -A 2 "TODO" rtables/R > TODOs.txt
  #     - store_artifacts:
  #         path: TODOs.txt
  #         destination: TODOs.txt

workflows:
  version: 2
  Rworkflow:
    jobs:
      - roxygen
      - pkgdown:
          requires:
            - roxygen
      - build_check_install:
          requires:
            - roxygen
      # - TODOs
